output_dir = "estampo_output"

[pipeline]
stages = ["load", "arrange", "plate", "slice", "resolve_templates", "pack"]

[plate]
size = [256, 256]

[slicer]
engine = "cura"
version = "5.12.0"

[slicer.cura]
printer = "bambox_p1s_ams"
filaments = ["PLA"]

[slicer.cura.overrides]
hole_xy_offset = 0.1
speed_wall_0 = 30
adhesion_type = "brim"
brim_width = 8
speed_layer_0 = 20
material_bed_temperature = 60
cool_fan_full_layer = 4

[[parts]]
file = "test_plate_2.5mm.step"

[[parts]]
file = "test_plate_3.0mm.step"

[[parts]]
file = "test_plate_3.5mm.step"

[[parts]]
file = "test_plate_4.0mm.step"

[resolve_templates]
command = "cura-p1s resolve {sliced_dir}/plate.gcode --settings {cura_settings}"
docker=true

[pack]
command = "bambox pack {sliced_dir}/plate.gcode -o {output_dir}/plate.gcode.3mf"
output = "{output_dir}/plate.gcode.3mf"
